In [1]:
from keras.models import load_model
# model.save
new_model = load_model('/content/drive/My Drive/Augmented/all_data/model_3_drugs1.h5')
new_model

In [4]:
%matplotlib inline

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import zipfile
import numpy as np
from google.colab import files
from keras.preprocessing import image
import cv2
from google.colab.patches import cv2_imshow

uploaded = files.upload()
tablet_count=0

for fn in uploaded.keys():
 
  # predicting images
  path = '/content/' + fn
  img = image.load_img(path, target_size=(400, 400))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = new_model.predict(images/255.0, batch_size=1)
  
  print(classes)
  print(classes[0])
  class_arg=np.argmax(classes[0])

  if class_arg==1:
    print("\n Dolo 650 mg")
  elif class_arg==2:
    print("\n Diamicron XR 60")
  elif class_arg==0:
    print("\n Karvol Plus")
  else:
    print("none of these")


Saving d1.jpeg to d1.jpeg
[[1.0000000e+00 6.5287194e-12 1.9022013e-25]]
[1.0000000e+00 6.5287194e-12 1.9022013e-25]

 Karvol Plus


In [5]:
def Tablet_Prediction(path):
  img = image.load_img(path, target_size=(400, 400))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = new_model.predict(images/255.0, batch_size=1)
  
  print(classes[0])
  class_arg=np.argmax(classes[0])

  if class_arg==1:
    print("\n Dolo 650 mg")
    return "Dolo 650 mg"
  elif class_arg==2:
    print("\n Diamicron XR 60")
    return "Diamicron XR 60"
  elif class_arg==0:
    print("\n Karvol Plus")
    return "Karvol Plus"
  else:
    print("none of these")

In [7]:
def Tablet_Count(path):
  #img = cv2.imread("dolo complete strip cropped.jpg")
  img = cv2.imread(path)
  img = cv2.resize(img,(640,480))
  ##cv2_imshow(img)
  img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
  img_hsv = cv2.resize(img_hsv,(640,480))

  #lower and upper values set for dolo
  lower= np.array([77, 77, 148])
  upper= np.array([104, 191, 255])
  mask= cv2.inRange(img_hsv, lower, upper)
  imgResult=cv2.bitwise_and(img,img,mask=mask)
  #cv2_imshow(imgResult)
  #cv2.waitKey(0)

  imgBGR=cv2.cvtColor(imgResult,cv2.COLOR_HSV2BGR)
  imgGray=cv2.cvtColor(imgResult,cv2.COLOR_BGR2GRAY)

  contours, hierarchy = cv2.findContours(imgGray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

  counter=0
  contour_list = []
  for contour in contours:
      approx = cv2.approxPolyDP(contour,0.01*cv2.arcLength(contour,True),True)
      area = cv2.contourArea(contour)
      if ((len(approx) > 8) & (len(approx) < 23) & (area > 1000)):
          contour_list.append(contour)
          counter=counter+1

  #Displaying the results
  #cv2.drawContours(imgGray, contour_list,  -1, (255,0,0), 2)
  #cv2_imshow(imgGray)
  print("\n Count of tablets: ",counter)
  return counter

In [8]:
def PredictOCR(path,filename):
  project = 'Bot-Genie'
  APIKey= "AIzaSyC_kVh24vbGMLS55QSudIjlfXOwnKK50VQ"
  bucketName = 'tab_bucket'
  bucketFolder = 'Images'
  localFile = filename
  storage_client = storage.Client.from_service_account_json('/content/drive/My Drive/Augmented/all_data/Bot-Genie-75a3b43c9332.jsond')

  # Make an authenticated API request
  buckets = list(storage_client.list_buckets())
  print(buckets)
  bucket = storage_client.get_bucket(bucketName)

  def upload_files(bucketName):
      """Upload files to GCP bucket."""
      #localFile = "IMG_5162.jpg"
      blob = bucket.blob(bucketFolder +"/"+ localFile)
      blob.upload_from_filename(path)
      return f'Uploaded {localFile} to "{bucketName}" bucket.'

  def list_files(bucketName):
      """List all files in GCP bucket."""
      files = bucket.list_blobs(prefix=bucketFolder)
      fileList = [file.name for file in files if '.' in file.name]
      return fileList

  def delete_file(bucketName, bucketFolder, fileName):
      """Delete file from GCP bucket."""
      bucket.delete_blob(bucketFolder +"/"+ fileName)
      return f'{fileName} deleted from bucket.'

  def ocr_extract():
    IMAGE="gs://tab_bucket/Images/"
    IMAGE=IMAGE+localFile
    vservice = build('vision', 'v1', developerKey=APIKey)
    request = vservice.images().annotate(body={
        'requests': [{
          'image': {
              'source': {
                'gcs_image_uri': IMAGE
              }
          },
          'features': [{
              'type': 'TEXT_DETECTION',
              'maxResults': 3,
            }]
        }],
      })
    responses = request.execute(num_retries=3)
    #print(responses['responses'][0]['textAnnotations'][0]['description'])
    text=responses['responses'][0]['textAnnotations'][0]['description']
    return text

  def extract_expdate(ocrtext):
    now = datetime.now() # current date and time
    cur_year = int(now.strftime("%Y"))

    print(search_dates(ocrtext))
    a=search_dates(ocrtext)
    dates=[]
    if(len(a)>0):
      for i in range(len(a)):
        timestamp = datetime.strptime(str(a[i][1]), '%Y-%m-%d %H:%M:%S')
        year=timestamp.year
        #print("timestamp", timestamp) 
        if(year>(cur_year-5) and year<(cur_year+5)):
          dates.append(a[i][1])
    print(dates)

    max_date=max(dates)
    return max_date.strftime("%B-%Y")

  #Uploading and listing files from bucket    
  print(list_files(bucketName))
  print(upload_files(bucketName))
  print(list_files(bucketName))

  #Extracting text and expiry date
  tab_text=ocr_extract()
  expdate=extract_expdate(tab_text)

  #Deleting the uploaded file from bucket
  print(delete_file(bucketName, bucketFolder, localFile))
  print(list_files(bucketName))
  print("\n Expiry date: ",expdate)
  return expdate

In [13]:
%matplotlib inline
!pip install dateparser
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

import zipfile
import cv2
import numpy as np
from google.colab import files
from keras.preprocessing import image

from datetime import datetime, timedelta
from dateparser.search import search_dates
from google.cloud import storage
from googleapiclient.discovery import build
import base64

uploaded = files.upload()
tablet_count=0

for fn in uploaded.keys():
 
  # predicting images
  path = '/content/' + fn
  print("Counting Tablets")
  tablet_count=Tablet_Count(path)
  if (tablet_count>0):
    predicted_tablet=Tablet_Prediction(path)
  else:
    Expiry_date=PredictOCR(path,fn)


Saving ocr1.jpg to ocr1.jpg
Counting Tablets

 Count of tablets:  3
[1.1708368e-15 6.7837323e-16 1.0000000e+00]

 Diamicron XR 60
